name: py2
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- cython
- delly
- blobtools
- numpy
- awscli
- samtools
- bcftools==1.9
- pybedtools
- pysam
- svdb
- svtools
- lumpy-sv
- svtools
- gsort
- svtyper
- python=2.7.14
- smoove
- pip:
  - vcf-kit
  - gsutil
prefix: /usr/local/var/pyenv/versions/miniconda3-4.3.27/envs/vcf-kit

